name: Publish to NPM
on:
    release:
        types: [published]
jobs:
    Publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 20
                  registry-url: 'https://registry.npmjs.org'
            - name: Install Required Packages
              run: npm install prettier eslint jest
            - name: Linting, Format and testing
              run: |
                  npm run lint
                  npm run format
                  npm run test
            - name: Publish
              run: |
                  npm ci
                  npm publish
                  env:
                    NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
