name: Publish to NPM
on:
    release:
        types: [created]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 20
                  registry-url: 'https://registry.npmjs.org'
            - name: Install dependencies and build
              run: npm ci && npm run build
            - name: Prettier
              run: npm run format
            - name: Publish package on NPM
              run: npm publish
